### ISSUE TITLE
登陆验证码不展示

### ISSUE THREAD

**Issue by jl621** [wanglelecc/laracms#10]
安装完之后有一些问题，打开都正常 后台登录的时候验证码不显示
软连接都已经添加过
/captcha/login?rOjwI9oe 500错误

ErrorException: ob_clean(): failed to delete buffer. No buffer to delete in file /var/www/html/laracms/vendor/mews/captcha/src/CaptchaController.php on line 23
Stack trace:
  1. ErrorException-&gt;() /var/www/html/laracms/vendor/mews/captcha/src/CaptchaController.php:23
  2. ob_clean() /var/www/html/laracms/vendor/mews/captcha/src/CaptchaController.php:23
  3. Mews\Captcha\CaptchaController-&gt;getCaptcha() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
  4. call_user_func_array() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
  5. Illuminate\Routing\Controller-&gt;callAction() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:45
  6. Illuminate\Routing\ControllerDispatcher-&gt;dispatch() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Routing/Route.php:212
  7. Illuminate\Routing\Route-&gt;runController() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Routing/Route.php:169
  8. Illuminate\Routing\Route-&gt;run() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Routing/Router.php:658
  9. Illuminate\Routing\Router-&gt;Illuminate\Routing\{closure}() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
 10. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:41
 11. Illuminate\Routing\Middleware\SubstituteBindings-&gt;handle() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 12. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 13. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:68
 14. Illuminate\Foundation\Http\Middleware\VerifyCsrfToken-&gt;handle() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 15. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 16. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49
 17. Illuminate\View\Middleware\ShareErrorsFromSession-&gt;handle() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 18. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 19. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:63
 20. Illuminate\Session\Middleware\StartSession-&gt;handle() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 21. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 22. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37
 23. Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse-&gt;handle() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 24. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 25. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:66
 26. Illuminate\Cookie\Middleware\EncryptCookies-&gt;handle() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 27. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 28. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:102
 29. Illuminate\Pipeline\Pipeline-&gt;then() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Routing/Router.php:660
 30. Illuminate\Routing\Router-&gt;runRouteWithinStack() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Routing/Router.php:635
 31. Illuminate\Routing\Router-&gt;runRoute() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Routing/Router.php:601
 32. Illuminate\Routing\Router-&gt;dispatchToRoute() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Routing/Router.php:590
 33. Illuminate\Routing\Router-&gt;dispatch() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:176
 34. Illuminate\Foundation\Http\Kernel-&gt;Illuminate\Foundation\Http\{closure}() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
 35. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /var/www/html/laracms/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php:65
 36. Barryvdh\Debugbar\Middleware\InjectDebugbar-&gt;handle() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 37. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 38. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /var/www/html/laracms/vendor/fideloper/proxy/src/TrustProxies.php:56
 39. Fideloper\Proxy\TrustProxies-&gt;handle() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 40. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 41. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:30
 42. Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 43. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 44. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:30
 45. Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 46. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 47. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27
 48. Illuminate\Foundation\Http\Middleware\ValidatePostSize-&gt;handle() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 49. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 50. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:46
 51. Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode-&gt;handle() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 52. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 53. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /var/www/html/laracms/vendor/dingo/api/src/Http/Middleware/Request.php:111
 54. Dingo\Api\Http\Middleware\Request-&gt;handle() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 55. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 56. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:102
 57. Illuminate\Pipeline\Pipeline-&gt;then() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:151
 58. Illuminate\Foundation\Http\Kernel-&gt;sendRequestThroughRouter() /var/www/html/laracms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:116
 59. Illuminate\Foundation\Http\Kernel-&gt;handle() /var/www/html/laracms/public/index.php:55

**Comment by jl621** [comment]
权限都给的777

**Comment by wanglelecc** [comment]
看一下GD库是否打开
