### ISSUE TITLE
2018_11_08_090102_seed_district_data.php文件过大，内存溢出了

### ISSUE THREAD

**Issue by youxu** [wanglelecc/laracms#14]
2018_11_08_090102_seed_district_data.php  这个文件太大了php artisan migrate会报错，phpini里面配置的128m内存都不够，我查看了下这个文件有555856行，能不能分开多个文件处理。

PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /git/laracms/vendor/wanglelecc/laracms-framework/database/migrations/2018_11_08_090102_seed_district_data.php on line 126077

**Comment by FraserProvan2** [comment]
yes

**Comment by wanglelecc** [comment]
暂时先将内存调整到 256M 吧，里面还有一个中文分词128M肯定是不够的。后期优化;
