### ISSUE TITLE
 Base table or view not found: 1146 Table 'cms.lara_settings' doesn't exis 没有对应的表？没有看到其他迁移文件了

### ISSUE THREAD

**Issue by hzw2579** [wanglelecc/laracms#16]
Base table or view not found: 1146 Table 'cms.lara_settings' doesn't exis

**Comment by wanglelecc** [comment]
这个错误有点像是没有迁移成功

**Comment by hzw2579** [comment]
我看了下你的文件，你的主分支里面的迁移文件只有两个，但是你的旧版本是有全部的！

**Comment by xueyangkk** [comment]
这个问题好像一直没修复  现在没办法链接上数据包 能否提供一份sql 文件 谢谢
