### ISSUE TITLE
Class App\User does not exist

### ISSUE THREAD

**Issue by hzw2579** [wanglelecc/laracms#17]
E:\cms\cms\vendor\laravel\framework\src\Illuminate\Routing\RouteSignatureParameters.php#

**Comment by wanglelecc** [comment]
App\User 已修改成 App\Models\User

**Comment by wanglelecc** [comment]
根据你提示的错误信息，看看是在哪调用的 App\User ,然对比一下github 上的源码。这个错误在之前确实有，但已经都修改过了，看看是不是你下载的代码版本不一致造成的

**Comment by 35924784** [comment]
1、<img width="562" alt="default" src="https://user-images.githubusercontent.com/5801601/49290406-e0bb7280-f4e1-11e8-8d08-0be482f0d5a1.png">
后台用户管理报错，请大家按照上图修改即可。
2、前端icon显示不全可按照如下图修改：
<img width="784" alt="default" src="https://user-images.githubusercontent.com/5801601/49290529-2841fe80-f4e2-11e8-99b4-9697a706ae0a.png">
保存文件，然后再执行一次如下命令：
php artisan vendor:publish --tag=public

**Comment by wanglelecc** [comment]
感谢反馈。但是不推荐此方法修改，如再发现此类问题，可自行 Fork 修复后 PR 给我。或者直接告知我来修复更新，以保持后续能正常更新。当前问题我已修复并更新，请稍后查看源码重试一下。

**Comment by wanglelecc** [comment]
可以加入 QQ 群：172960867，及时沟通反馈 。

**Comment by wanglelecc** [comment]
@35924784

**Comment by wanglelecc** [comment]
该问题已修复，如果还是存在此问题，请将报错位置的代码与 github 比对一下，看看是否代码一致

**Comment by zccxvas110** [comment]
![image](https://user-images.githubusercontent.com/24209096/50502228-930e3780-0a98-11e9-8b1e-7ba76df172df.png)
![image](https://user-images.githubusercontent.com/24209096/50502240-a4574400-0a98-11e9-94f7-7e2a379b7eb8.png)
修改引入的路径即可

**Comment by wanglelecc** [comment]
再次申明一下，该问题已2018.11月已修复。再次出现这个问题是因为国内的某composer源的缓存导致。可以自行与github上的代码对比。建议更换源：https://learnku.com/laravel/composer
