### ISSUE TITLE
文章提交回复Attribute 'data-setup' in element 'video' not supported

### ISSUE THREAD

**Issue by qingyi12345** [wanglelecc/laracms#19]
ErrorException thrown with message "**Attribute 'data-setup' in element 'video' not supported (for information on implementing this, see the support forums)** "

Stacktrace:
#81 ErrorException in F:\sites\laracms\vendor\ezyang\htmlpurifier\library\HTMLPurifier\HTMLDefinition.php:379
.......

**Comment by wanglelecc** [comment]
HTMLPurifier 新版不兼容了，手动移除一下吧
