### ISSUE TITLE
使用composer安装过程中出错

### ISSUE THREAD

**Issue by fenghoer** [wanglelecc/laracms#22]
Extracting archive  - Installing wanglelecc/laracms-framework (dev-master b95ac b0): Downloading https://dl.laravel-china.org/wanglelecc/laracms-framework/b95ac b0a2ca12e2afec8cd922ec1ac513c7401e7.zip                                          Downloading (failed)                                                             Failed: [Composer\Downloader\TransportException] 404: The "https://dl.laravel-ch ina.org/wanglelecc/laracms-framework/b95acb0a2ca12e2afec8cd922ec1ac513c7401e7.zi p" file could not be downloaded (HTTP/1.1 404 Not Found)                         Downloading https://api.github.com/repos/wanglelecc/laracms-framework/zipball/b9 5acb0a2ca12e2afec8cd922ec1ac513c7401e7                                           Downloading (connecting...)
--

还有下面的字体为红色的提示：

[RuntimeException]                                                               Failed to execute git checkout "b95acb0a2ca12e2afec8cd922ec1ac513c7401e7" -      - && git reset --hard "b95acb0a2ca12e2afec8cd922ec1ac513c7401e7" --                                                                                               fatal: reference is not a tree: b95acb0a2ca12e2afec8cd922ec1ac513c7401e7
--

是不是composer资源包不能用导致的？

**Comment by wanglelecc** [comment]
源不稳定导致的
