### ISSUE TITLE
发表文章评论时报错

### ISSUE THREAD

**Issue by myhui0926** [wanglelecc/laracms#24]
报错信息：

> "Attribute 'data-setup' in element 'video' not supported (for information on implementing this, see the support forums) "

初步判定是HTMLPurifier服务报错，解决办法：
修改config/purifier.php文件的以下部分：
`'user_article_body' => [
            'HTML.Doctype'             => 'XHTML 1.0 Transitional',
            'HTML.Allowed'             => 'div,b,strong,i,em,a[href|title],ul,ol,ol[start],li,p[style],br,span[style],video[class|controls|preload|width|height|src|data-setup],img[width|height|alt|src],*[style|class],pre,hr,code,h2,h3,h4,h5,h6,blockquote,del,table,thead,tbody,tr,th,td',
            'CSS.AllowedProperties'    => 'font,font-size,font-weight,font-style,margin,width,height,font-family,text-decoration,padding-left,color,background-color,text-align',
            'AutoFormat.AutoParagraph' => true,
            'AutoFormat.RemoveEmpty'   => true,
        ],`
将`video[class|controls|preload|width|height|src|data-setup]`中的data-setup删除即可
删除后：
`video[class|controls|preload|width|height|src]`
不是很清楚具体的原因，是否是因为HTMLPurifier不支持HTML5自定义属性造成的？

**Comment by wanglelecc** [comment]
HTMLPurifier 最近发布的几个版本，确实存在不兼容之前的用法问题。你先删除掉配置，我再找找有没有可替代的
