### ISSUE TITLE
请教下老师，ueditor编辑器上传图片时候失败，419 (unknown status)该怎么解决？

### ISSUE THREAD

**Issue by somesssii** [wanglelecc/laracms#27]
![image](https://user-images.githubusercontent.com/35617655/59238442-c1d82e80-8c30-11e9-81b9-5e4dde10d8e3.png)

**Comment by wanglelecc** [comment]
看一下具体报错信息，根据错误信息，定位错误的位置。。。顺藤摸瓜

**Comment by somesssii** [comment]
![image](https://user-images.githubusercontent.com/35617655/59257312-498d5f80-8c68-11e9-9e4a-f874b6dbbab5.png)
![image](https://user-images.githubusercontent.com/35617655/59257425-80fc0c00-8c68-11e9-84e8-2537b8b792e7.png)
提示js错误，不过我觉得错误应该不是这个。

**Comment by wanglelecc** [comment]
这不是异步上传图片吗？看一下请求返回的内容啊，哪里可能就有明确的错误信息

**Comment by somesssii** [comment]
返回的内容没有错误信息

**Comment by somesssii** [comment]
你好，当我将项目部署到服务器后，幻灯片的图片上传功能就报错，图片可以上传，但是storage不能自动生成文件夹。
![image](https://user-images.githubusercontent.com/35617655/59401167-722e6a00-8dcc-11e9-9879-81279e4a0c93.png)

**Comment by wanglelecc** [comment]
https://learnku.com/docs/laravel/5.8/filesystem/3918
