### ISSUE TITLE
响应式的菜单栏

### ISSUE THREAD

**Issue by chichoyi** [wanglelecc/laracms#5]
移动端的菜单栏需要调整哦，博主。要不要人手帮你开发这个东西

**Comment by wanglelecc** [comment]
感谢反馈。目前 laracms 还处于生长阶段，很多设计还没有经过实际的检验，等成熟一些了。再考虑这个... 你如果有兴趣可以 fork 一个自己搞搞。也可以等后面都稳定了，再一起合作开发。

**Comment by chichoyi** [comment]
因为我现在要用到这个来二次开发了，我看看手机端菜单要怎么搞

**Comment by wanglelecc** [comment]
看你需求。可以在页面上做兼容，也可以单独为手机端分离一套模板主题出来, 都是可以的，可以到 config/theme.php 看看
