### ISSUE TITLE
报错哦  

### ISSUE THREAD

**Issue by jianwoo** [wanglelecc/laracms#9]
In Connection.php line 664:
                                                                               
  SQLSTATE[HY000] [2002] Connection refused (SQL: insert into `lara_users` (`  
  created_at`, `email`, `introduction`, `name`, `password`, `remember_token`,  
   `status`, `updated_at`) values (2018-09-27 15:22:59, admin@56br.com, Codin  
  g 改变世界！, admin, $2y$10$vTd0rUBZdBkfWFUfAStGv.ISB1jGS2WNrof0VnD5KuA.pyO  
  sn9H.y, 8huzpUa9cu, 1, 2018-09-27 15:22:59), (2018-09-27 15:23:00, wll@56br  
  .com, Coding 改变世界！, wll, $2y$10$mQdsBfENmU8G4mZFCmzYI.waISv5tlKFuqP9Tf  
  6PuQzGl2AOMwCgW, 1UuVZ4iqs7, 1, 2018-09-27 15:23:00))                        
                                                                               

In PDOConnection.php line 50:
                                             
  SQLSTATE[HY000] [2002] Connection refused  
                                             

In PDOConnection.php line 46:
                                             
  SQLSTATE[HY000] [2002] Connection refused  

老哥啥情况

**Comment by wanglelecc** [comment]
检查一下数据库配置文件，确认一下所配置的 数据库 用户名 和 密码 能正常登入mysql

**Comment by jianwoo** [comment]
嗯  刚好查过  已经可以了
